"""Data card: sources, dates, counts, class balance and dedup stats, written to reports/."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from data_pipeline.split import TEST, TRAIN


def _date_range(dates: pd.Series) -> tuple[str, str]:
    d = dates.dropna()
    if d.empty:
        return "n/a", "n/a"
    return d.min().date().isoformat(), d.max().date().isoformat()


def split_summary(df: pd.DataFrame, split: pd.Series) -> list[dict]:
    rows = []
    for name in sorted(split.unique()):
        part = df.loc[split == name]
        start, end = _date_range(part["date"])
        rows.append(
            {
                "part": name,
                "rows": len(part),
                "phishing": int(part["label"].sum()),
                "benign": int((part["label"] == 0).sum()),
                "phishing_pct": round(100 * part["label"].mean(), 2) if len(part) else 0.0,
                "domains": part["domain"].nunique(),
                "date_min": start,
                "date_max": end,
            }
        )
    return rows


def dataset_card(
    name: str, meta: dict, df: pd.DataFrame, splits: dict[str, pd.Series], extra: dict
) -> dict:
    start, end = _date_range(df["date"])
    return {
        "dataset": name,
        "license": meta.get("license", ""),
        "rows_after_dedup": len(df),
        "phishing": int(df["label"].sum()),
        "benign": int((df["label"] == 0).sum()),
        "phishing_pct": round(100 * df["label"].mean(), 2) if len(df) else 0.0,
        "domains": df["domain"].nunique(),
        "date_min": start,
        "date_max": end,
        "undated_rows": int(df["date"].isna().sum()),
        "with_html": int(df["has_html"].sum()) if "has_html" in df else 0,
        "sources": df["source"].value_counts().to_dict(),
        "splits": {k: split_summary(df, v) for k, v in splits.items()},
        **extra,
    }


def render_markdown(cards: list[dict]) -> str:
    out = [
        "# Data card",
        "",
        "Generated by `python -m data_pipeline build`. Do not edit by hand.",
        "Labels: 1 = phishing (or malicious for URLhaus), 0 = benign. Splits are by registered "
        "domain (eTLD+1); no domain appears in both train and test.",
        "",
    ]
    for c in cards:
        out += [
            f"## {c['dataset']}",
            "",
            f"- License: {c['license']}",
            f"- Rows loaded: {c['load']['rows_loaded']:,} "
            f"(unparsable URLs dropped: {c['load']['rows_unparsable_url']:,})",
            f"- Dedup: {c['dedup']['exact_duplicates']:,} exact URL duplicates, "
            f"{c['dedup']['label_conflicts']:,} rows with conflicting labels, "
            f"{c['dedup']['near_duplicate_html']:,} near-identical HTML pages removed",
            f"- After dedup: {c['rows_after_dedup']:,} rows, {c['domains']:,} domains, "
            f"{c['phishing']:,} phishing / {c['benign']:,} benign ({c['phishing_pct']}% phishing)",
            f"- Dates: {c['date_min']} to {c['date_max']} ({c['undated_rows']:,} undated rows)",
            f"- Rows with HTML: {c['with_html']:,}",
            f"- Sources: {', '.join(f'{k} ({v:,})' for k, v in c['sources'].items())}",
        ]
        if c.get("time_cutoff"):
            out.append(f"- Time-split cutoff: {c['time_cutoff']}")
        for note in c.get("notes", []):
            out.append(f"- Note: {note}")
        for split_name, rows in c["splits"].items():
            out += [
                "",
                f"**{split_name} split**",
                "",
                "| part | rows | phishing | benign | % phishing | domains | from | to |",
                "| --- | ---: | ---: | ---: | ---: | ---: | --- | --- |",
            ]
            for r in rows:
                out.append(
                    f"| {r['part']} | {r['rows']:,} | {r['phishing']:,} | {r['benign']:,} | "
                    f"{r['phishing_pct']} | {r['domains']:,} | {r['date_min']} | {r['date_max']} |"
                )
        out.append("")
    return "\n".join(out)


def card_table(cards: list[dict]) -> pd.DataFrame:
    rows = []
    for c in cards:
        for split_name, parts in c["splits"].items():
            for r in parts:
                if r["part"] in (TRAIN, TEST):
                    rows.append({"dataset": c["dataset"], "split": split_name, **r})
    return pd.DataFrame(rows)


def write_card(cards: list[dict], reports_dir: Path) -> tuple[Path, Path]:
    reports_dir = Path(reports_dir)
    (reports_dir / "tables").mkdir(parents=True, exist_ok=True)
    md = reports_dir / "data_card.md"
    csv = reports_dir / "tables" / "data_card.csv"
    md.write_text(render_markdown(cards), encoding="utf-8")
    card_table(cards).to_csv(csv, index=False)
    return md, csv
